var audioTableABX = [
    [
      'audio/-6dB.wav',
      'audio/0dB.wav'
    ],
    [
      'audio/-3dB.wav',
      'audio/-6dB.wav'
    ],
    [
      'audio/-3dB.wav',
      'audio/-1.5dB.wav'
    ],
    [
      'audio/-2dB.wav',
      'audio/-3dB.wav'
    ],
    [
      'audio/-3.5dB.wav',
      'audio/-3dB.wav'
    ],
    [
      'audio/-3dB.wav',
      'audio/-2dB.wav'
    ],
    [
      'audio/-3.5dB.wav',
      'audio/-3.2dB.wav'
    ],
  ];